// Autogenerated with DRAKON Editor 1.31


function AMainDrakon() {
    // item 61
    price_Paint();
}

function NS() {
    // item 37
    /**
    В JS фукнция это глобальная переменная
    
    function NS(){
    }
    
    function global_test() {
      // Вывод глобальной переменной после вызова функции
      NS.glob = 'glob';
      Logger.log(NS.glob);
      NS.glob = 'q';
      Logger.log(NS.glob);
    }
    */
}

function assert(condition) {
    // item 55
    condition ? Logger.log('Test Passed!') : Logger.log('Test Failed!');
}

function cell_Has(cell, regex) {
    // item 43
    return  cell	
    	.getValue()
    	.toString()
    	.trim()
    	.split(',')
    	.filter(
    	    element => regex.test(element))
    	.length > 0;
}

function cell_Has_test() {
    // item 49
    regex = /\d{3}-\d{3}-\d{4}/;
    
    sheet = SpreadsheetApp
    	.getActiveSpreadsheet()
    	.getSheetByName('Прайс без НДС')
    // item 62
      // Тест 1: ячейка содержит SKU
    cellWithSKU = sheet.getRange('Q123');
    // item 63
    if (cell_Has(cellWithSKU, regex)) {
        
    } else {
        // item 66
         Logger.log('ошибка 1');
    }
    // item 67
      // Тест 2: ячейка не содержит SKU
      cellWithoutSKU = sheet.getRange('A1');
    // item 68
    if (cell_Has(
	cellWithoutSKU, 
	regex)) {
        // item 71
        Logger.log('ошибка 2');
    } else {
        
    }
}

function price_Paint(cell) {
    var _sw150000_ = 0;
    // item 150000
    _sw150000_ = cell_Has(cell, /\d{3}-\d{3}-\d{4}/);
    // item 150001
    if (_sw150000_ === true) {
        // item 23
        SKUS_History_Update();
        // item 27
        price_BackGrounds_Update();
    } else {
        // item 150002
        if (_sw150000_ === false) {
            
        } else {
            // item 150003
            throw "Unexpected switch value: " + _sw150000_;
        }
    }
}



